### ISSUE TITLE
Readme has no install instructions

### ISSUE THREAD

**Issue by calebmeyer** [OldhamMade/ll#39]
I've never used Nim, and I'm not opposed to doing it. I just don't want to jump in to a whole language ecosystem (especially via the windows subsystem for linux) without any guidance.

Can you add instructions to the readme for installing this? Or provide a binary in your releases?

**Comment by OldhamMade** [comment]
@calebmeyer installation instructions added. Binary releases are planned, but I'm waiting to address #34 before publishing `ll` as an installable binary.

**Comment by calebmeyer** [comment]
Thanks for the quick response. Looking forward to using this more!
